### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by dlandrum** [SCCapstone/DebtCalculator#133]
The URL of our project is https://debt-calculator-csce-490.appspot.com/. 
On our homepage is a link to a video tutorial that explains our app, which redirects the user to https://debt-calculator-csce-490.appspot.com/info, which is where the video is embedded, along with the screenshots of our app in use.
The URL of the video on youtube is https://www.youtube.com/watch?v=SSx44zOY1XA.

**Comment by josemvidal** [comment]
Got it.
